version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: course_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/seed_data.sql:/docker-entrypoint-initdb.d/2_seed.sql

volumes:
  mysql_data:
