APP_TITLE = "Course Registration System"
APP_WIDTH = 1000
APP_HEIGHT = 650

PRIMARY_COLOR = "#2c3e50"
SECONDARY_COLOR = "#3498db"
BG_COLOR = "#ecf0f1"

FONT_TITLE = ("Arial", 16, "bold")
FONT_NORMAL = ("Arial", 11)

ROLE_ADMIN = "ADMIN"
ROLE_STUDENT = "STUDENT"

MAX_CREDITS_PER_SEMESTER = 24